"""Create table Tin

Revision ID: d0b3180e55b5
Revises: d27f35d70abf
Create Date: 2021-12-10 20:14:22.838830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b3180e55b5'
down_revision = 'd27f35d70abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('images', sa.String(length=255), nullable=True),
    sa.Column('id_Loaitin', sa.Integer(), nullable=True),
    sa.Column('tomtat', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_Loaitin'], ['loai_tin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tin')
    # ### end Alembic commands ###
