"""Create table LoaiTin

Revision ID: d27f35d70abf
Revises: 0275b69a91ad
Create Date: 2021-12-10 14:51:39.013862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27f35d70abf'
down_revision = '0275b69a91ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loai_tin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenloai', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loai_tin')
    # ### end Alembic commands ###
